### ISSUE TITLE
crashes while opening image from telegram

### ISSUE THREAD

**Issue by reverendhomer** [SimpleMobileTools/Simple-Gallery#107]
Steps to reproduce:
* send picture as file in telegram chat
* try to open it without saving in gallery

**Comment by Larx** [comment]
Same when opening an email attachment from K9-Mail.

**Comment by tibbi** [comment]
hello, please recheck with 2.2.1 which Im publishing now, a couple things have changed

**Comment by Larx** [comment]
2.2.1 still crashes when opening image attachments from K9-Mail.

**Comment by bwurst** [comment]
I can confirm the k9-mail bug with 2.1.3, the newest that fdroid offers.

**Comment by Larx** [comment]
...The same problem when opening MMS pictures with QKSMS or the default CM MMS app.

**Comment by tibbi** [comment]
ye MMS is a different issue, I know about that one. Ive spent quite a few hours trying to fix MMS, but its such a ridiculous system that i just couldnt do it. Hopefully at the next run Ill be more successfull.

**Comment by reverendhomer** [comment]
>hello, please recheck with 2.2.1 which Im publishing now, a couple things have changed

Nope, still crashing.

**Comment by jpbaril** [comment]
Opening images from K9-Mail still crashes on 2.2.3

**Comment by tibbi** [comment]
K9-Mail should be fixed with 2.3.1 which Ill release later. Havent tested telegram, hope it was the same issue.

**Comment by Larx** [comment]
K9 works, QKSMS MMS still not.

**Comment by tibbi** [comment]
ill close this issue then, MMS is a separate issue at #82

**Comment by reverendhomer** [comment]
Reopen this issue, please. Original report was about telegram, and 2.3.0 still crashes.

**Comment by tibbi** [comment]
aha true, it just got hijacked :)

**Comment by Larx** [comment]
That was me. Looked like the same problem.

**Comment by Larx** [comment]
However, as currently opening images with K9 mails fails once again, I'll hijack once more...

**Comment by tibbi** [comment]
it used to work already but broke with 2.2.3 again, or what do you mean?

**Comment by reverendhomer** [comment]
On Mon, Jan 16, 2017 at 08:59:49AM -0800, Tibor Kaputa wrote:
> it used to work already but broke with 2.2.3 again, or what do you mean?
I, personally, didn't test K9 with 2.2.3, but 2.3.0 crashes with attached image
in K9

R.H.

**Comment by Larx** [comment]
I use 2.3.2. I can't say when, but sometimes opening images from K9Mail still crashes. It might be because of the app 'Better Open With', which I sometimes use. This app hooks into the opening process and gives you a configurable time to chose the app you want to open with, then opens a defined default app.
Another option might be that the images are not yet downloaded from the IMAP server, when Gallery crashes trying to open them. This would explain why it sometimes works.
However, currently I'm still guessing... Seems a bit random to me at the moment.

**Comment by tibbi** [comment]
i was testing Telegram with 2.3.4, but cannot reproduce the crash. First of they have an own viewer for images, and if I send an image as a file so I dont see its preview, then click on it and open via simple gallery, it displays just fine.

**Comment by reverendhomer** [comment]
well, I cannot retry with 2.3.4, because it is not in F-droid. Current version in f-droid is 2.3.3 and I can reproduce the problem with it.

**Comment by Larx** [comment]
As for K9Mail (not that I want to completely hijack the thread), opening images once did work, but 2.3.4 works no longer.

**Comment by reverendhomer** [comment]
>As for K9Mail (not that I want to completely hijack the thread), opening images once did work, but 2.3.4 works no longer.

Yep, 2.3.3 works just fine with K9

**Comment by tibbi** [comment]
ok ill recheck it, move all K9 related stuff to #151

**Comment by reverendhomer** [comment]
Fixed in 2.3.5, thank you!
