### ISSUE TITLE
Show folders with .nomedia

### ISSUE THREAD

**Issue by kinclma1** [SimpleMobileTools/Simple-Gallery#150]
Hello, is it possible to add showing folders with `.nomedia` in the folder view when "Show hidden folders" is selected in the menu? When I open an image from the file manager, it displays, but the folder still doesn't show up in the folders view in the app.

Edit: Even if the folders could be added manually, it would be great (if not possible to automate it)

**Comment by tibbi** [comment]
Hello, files hidden with .nomedia should already be shown if that item in Settings is checked. It affects both .nomedia folders and folders hidden inside the app. If they still dont show, its some other issue.

**Comment by kinclma1** [comment]
I don't know whether it could be caused by the old system (Android 4.1), or potentially by folder hierarchy, but when I hide a folder using QuickPic (adds .nomedia), it can't be shown in this gallery.

**Comment by kinclma1** [comment]
When I tried hiding the root "Pictures" folder in QuickPic and unhiding it again. It no longer shows in the app, even if the .nomedia file is no longer there.

**Comment by tibbi** [comment]
try creating and deleting the .nomedia file with some popular file explorer, if it changes anything

**Comment by touzainanboku** [comment]
Based on what was said on #95 I tried creating a new folder using Amaze, put a few images in it and then created a .nomedia in it. It doesn't appear in the app (Show hidden folders is enabled). In my experience it doesn't show any of my hidden folders, regardless of which app was used to create the .nomedia (QuickPic. Solid Explorer, MiXplorer, and now Amaze).

**Comment by tibbi** [comment]
i can doublecheck, but it worked fine on all my devices

**Comment by kinclma1** [comment]
It looks like QuickPic is doing something more than just adding .nomedia. When I unhid a folder in QuickPic and then added .nomedia in SimpleMobileTools file manager, it works as expected.

Although, I have a folder containing images, which also contains other folders with images. When I added .nomedia to this folder, it shows up, but not the child folders.

**Comment by Jalbre2** [comment]
This has never worked for me whatsoever. Most of my .nomedia files have been added by Syncthing and Quickpic. But this seems to be the only app I have encountered where it matters what program created the file.

**Comment by tibbi** [comment]
Hey, is it better already? There has been some refactoring of the way Im obtaining media files, related to .nomedia folders too.

**Comment by kinclma1** [comment]
Looks like the original problem is solved, but I can't open any image, just blank space appears and nothing happens (I have waited for cca 1 minute). Moreover I tried to hide an additional folder in QuickPic and it shows up in the no-hidden-folders view with "(hidden)" in the title.

**Comment by Jalbre2** [comment]
No sign of my hidden folders yet. I cleared appdata too, but oh well.

**Comment by touzainanboku** [comment]
Hidden folders are working for me now.

**Comment by Jalbre2** [comment]
They showed up! Amazing!

Unfortunately, I tried toggling the setting back off, and they still show up, lol. That's still progress though!
