### ISSUE TITLE
Allow keeping Date Modified at file copying

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#310]

**Comment by Theobald93** [comment]
That would be awesome! Stupid android always changes the date x_x

**Comment by gcalzo** [comment]
This may not be easy since as far as I know the problem is _embedded_ into Android! (if not rooted)

**Comment by tibbi** [comment]
I can easily set the Date Modified for files on the internal storage, not on SD card tho

**Comment by gcalzo** [comment]
I know what you mean (vfat limitation), but moving SD to SD should not change date/time as per all the other file managers/galleries I have tried so far. Maybe you are doing a safer copy&delete?

**Comment by tibbi** [comment]
Im not sure how should it be done, sd card file handling on Android is a nightmare, which gets more complicated with every Android version. Theres still a couple people with some issues I couldnt resolve, and Ive already seen more new things coming with Android 7 and 8.

**Comment by gcalzo** [comment]
Sincerely I do not know how to help you...
I can only say that moving files SD2SD with other gallery manager or with Solid Explorer is not changing date/time. And this is, for me, essentials when moving video to subfolders since videos do not have exif data with date/time and so the _sorting-by-date_ will not function correctly!
BTW: Motorola MotoG5 Plus with android 7...

**Comment by Ketrel** [comment]
There's a file manager called Amaze (available on F-Droid, so open source).

I've tried the following operations

**Rename:** Kept timestamp unaltered  
**Move:** Kept timestamp unaltered  
**Copy:** New file had current timestamp

That in mind, it should be possible to look at how they're handling the Rename and Move operations such that it doesn't alter the timestamp.

I'm not familiar with Java or Kotlin, so I'm not sure I could assist in the actual coding portion other than to point app I did for reference.

**Comment by tibbi** [comment]
I know how to do it on the internal storage, not sure about the SD card. Were the files you tested on an SD card? Thanks

**Comment by Ketrel** [comment]
My phone is a Oneplus 3T so I don't have an SD Card, however, I know someone who has a Note 8 w/ SDCard, and I'll be in their general vicinity tonight. I'll see if I can get them to install the same file manager app and test the rename/move/copy operations.  I'll report back once I do.

**Comment by gcalzo** [comment]
The app is on Google store too: https://play.google.com/store/apps/details?id=com.amaze.filemanager

Just tested on my MotoG5 plus working on SD card only and I confirm that rename & move keep date time! 👍 I really hope you'll be able to understand how to do it! ☺️

**Comment by Ketrel** [comment]
Excellent, that means there's definitely a way to do it for both storage types, and it's open source and can be referenced.  That's great news!

**Comment by tibbi** [comment]
well if its doable, I should be able to figure it out. Im not promising any date when will I get to it tho :)

**Comment by gcalzo** [comment]
Personally I'm crossing all my fingers because so far I still didn't found a good replacement for Google Photo since Lenovo/Motorola decided to drop their own gallery app on phone with Nougat! :(

**Comment by tibbi** [comment]
Ive changed something, it works in some cases. Setting last modified time apparently sometimes works, sometimes doesnt. There is a huge discussion about the bug report at https://issuetracker.google.com/issues/36930892 , it started at 2011 and it's still not done...

**Comment by Ketrel** [comment]
I'm curious, as it's currently implemented, what are you doing to move the file?  When I use a terminal emulator (like JuiceSSH or Termux), or ADB Shell, and use the `mv` command to move or rename, the modification time isn't touched regardless of location.  Is there possibly a way to send a raw command of that nature? 

I'd assume that may be consistent in not touching the modification time.  I'm aware that actually TRYing to set it has issues due to FUSE.  I run into that particular issue every time I transfer phones and end up having to be....'creative' to fix the timestamps.

**Comment by tibbi** [comment]
At renaming If the file is on the internal storage, I use the built in Rename function. If its on an SD card, it has to be handled differently, through the Storage Access Framework. At Move action I pretty much copy and delete the items, as renaming can be buggy if its being moved in a different folder, even if both the source and destination are on internal storage. File management on android is a nightmare, and its just getting worse with every new version...

**Comment by Ketrel** [comment]
Are you talking about `renameTo()`? 

If so, the issue with SD Cards is only when moving from internal to external storage and vice versa from what I've been reading.  Are you using a different function?

**Comment by tibbi** [comment]
`renameTo()` is used only when renaming a file on the internal storage. For copy/move I use different things. Ive checked some Amaze code, but if you check their reviews at https://play.google.com/store/apps/details?id=com.amaze.filemanager , they are having a lot of file handling related issues too. I dont want to copy any code blindly, I want to fix the issues properly by understanding the actual fixes.

**Comment by gcalzo** [comment]
It's a long, long time that I do not code (other than scripts) but for moving a file I would actually move it instead of copy/delete.
Anyway, feel free to use my phone for beta testing! I can use the app on two:
- my primary one with Nougat (Moto G5 plus, stock, not unlocked and so not rooted)
- my previous one (I use it for testing!) with Marshmallow (Moto G2, stock rom, unlocked and rooted)

**Comment by tibbi** [comment]
I would use some Move function too, if it was that simple :/ Theres many different people with different devices and issues, so I chose copy, comparing file sizes, and deleting only when everything is ok.

**Comment by gcalzo** [comment]
I understand your point of view and I **appreciate** 100% your _safe way_, but unfortunately that may suffer from the well known date/time FUSE problem.
Probably you have already found this https://forum.xda-developers.com/android/general/guide-timestamp-attributes-correct-t2960935 and that the problem should be _fixed_ with Android 8 where FUSE will not be used anymore (...and, thanks God, my Moto G5p should get Android 8! :) )
But I still wonder how other Gallery/File manager are able to move SD2SD without loosing attributes...

**Comment by tibbi** [comment]
I was always hoping for simplifying file management, but sadly its just getting more complicated with every android version, which is ridiculous. Only if you have your own app with many users and different devices you realise that even the simplest functions like `renameTo` on files on the internal storage sometimes fail. There have to be ways of making things work properly, but it really needs a huge amount of fine tuning, so theres still a long way to go.

**Comment by Ketrel** [comment]
Something I wanted to ask, when you say that `renameTo` is used when moving on internal storage, is that in the current version?  Because I'm using the Oneplus 3T which ONLY has internal storage (and using the latest fdroid version) and when I move files, they do get the timestamp changed.

**Comment by tibbi** [comment]
Im using `renameTo` only for renaming, for moving on the internal storage I still use copy/delete. RenameTo just didnt work well to some people.

**Comment by Ketrel** [comment]
Currently? Because as I said, my phone only has internal storage, but my timestamps are still changing when I move or rename a file.

(The Oneplus 3/3T doesn't support SDCards at all, so I can guarantee you I'm using internal storage)

**Comment by tibbi** [comment]
yes, right now for moving anything to anywhere I use copy/delete, that seems to work the best. Maybe some metadata is lost, but at least the files themselves are safe.

**Comment by Ketrel** [comment]
Ah ok, I thought you were saying renameTo was being used in the currently released version. 
I'll keep looking to see if I can find any options, but what is the risk at using renameTo with SD to SD again?

I know there's issues with Internal to SD or SD to Internal, but from what I'm reading SD to SD and Internal to Internal works fine. 

If that's the case, perhaps a quick function that checks if the storage location is the same and if it is, calls renameTo, and if not, uses the current copy+delete?

**Comment by tibbi** [comment]
There is no `renameTo` for SD card files, they are handled in a whole different way than internal storage files. I used to care if the files are on the internal storage or SD card and I was checking it at https://github.com/SimpleMobileTools/Simple-Commons/blob/26182701d126b57c9aab9cd4cad3c327c30395f6/commons/src/main/kotlin/com/simplemobiletools/commons/activities/BaseSimpleActivity.kt#L144 as thats what the common sense dictated me, but it simply didnt work well enough.

**Comment by Ketrel** [comment]
I'm a bit confused, I'm referencing https://developer.android.com/reference/java/io/File.html#renameTo(java.io.File)

I'm not seeing any indication that java.io.File is not available for SD->SD operations.  

Am I reading that wrong?

**Comment by tibbi** [comment]
its not mentioned there, but you cannot do the typical file operation on SD card files if you reference them as File. You have to use DocumentFile, which actually also has a renameTo(), but that just wasnt reliable enough either https://developer.android.com/reference/android/support/v4/provider/DocumentFile.html#renameTo(java.lang.String) . DocumentFile is a whole separate story, it once took me a whole saturday till I managed creating an empty file on an SD card on Android 5+.
Anyway, Ive added some lastModified setting after copy/move operations which should work in some cases, can you try this version? Just remove the ".zip" appendix from the filename and run it. Thanks :)
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/1362917/app-release.apk.zip)

**Comment by Ketrel** [comment]
I'll be able to give that a try this afternoon, but a couple questions.  In that one, you mention setting lastModified, is that for SD or Internal, because from what I understand, due to the FUSE stuff, that won't work for internal, and I don't have a phone with an SDCard to test with.

I can test anything using internal storage though.

**Comment by tibbi** [comment]
setting LastModified works only on some internal storages, never on SD card. It works on 1 of my devices, on 3 it doesnt.

**Comment by Ketrel** [comment]
I'm pretty sure it won't work on mine.  To modify timestamps on my device I need to boot into recovery (so storage isn't done through FUSE) and use a busybox binary for its touch command.

I'll give it a shot though.  Still for internal to internal, is there any reason not to use renameTo?

**Comment by tibbi** [comment]
It didnt work reliably in some cases, I dont remember exactly now. I used to do it like that as Ive linked. In the link you sent they also mention that `Many failures are possible.`. I might change it in the future and try renameTo first, and only if it fails, fall back to copy/delete.

**Comment by Ketrel** [comment]
That sounds like it would be the best option, especially since it has a return value like that.

Because changing the timestamp on a rename or move is best avoided if at all possible.  As much as I hate to say it, I've taken to moving images with another app when I move them out of my download folder so I don't lose my date sorting.

**Comment by gcalzo** [comment]
On MotoG5p move internal2internal is still changing the timestamp

**Comment by gcalzo** [comment]
On MotoG2 (rooted) move internal2internal is still changing the timestamp

**Comment by tibbi** [comment]
you can try sorting by Date Taken, thats not changed.

**Comment by gcalzo** [comment]
I know that and I confirm that EXIF metadata are not changed. But as I wrote the problem is with Video because they do not have EXIF data!

**Comment by Ketrel** [comment]
None of my photos have exif data, so I can't sort by anything other than file name, modification date, or size unfortunately.

**Comment by tibbi** [comment]
pngs neither ;)

**Comment by gcalzo** [comment]
@Ketrel, is that _by design_ or your choice?
I love EXIF and when I moved from my old Palm Treo 650 to the Moto G2 I have manually added the date/time fields as EXIF metadata! And _redate_ every file directly on the SD card mounted on pc because I quickly realized Android was loosing timestamps while copying from pc to phone! :-(
Initially I simply **hated** the MTP protocol, then I have learned that even with other tools the timestamp was lost due to the FUSE implementation... (BTW: I'm _playing_ with Android only since about 15 months!!)

**Comment by Ketrel** [comment]
Me? By choice.  

I strip EXIF data from everything I can.  I consider every part of that a security risk (reveals things I don't want to tell) or a hassle (tells the image to display differently than the pixel data).

**Comment by tibbi** [comment]
The new version 2.16.0 released soon will use the `renameTo` for moving from internal to internal, you can then check if its any better.

**Comment by gcalzo** [comment]
Internal only? ...I use the SD exclusively...

**Comment by tibbi** [comment]
then you will have to wait some more :)

**Comment by gcalzo** [comment]
...fingers crossed... :-)

**Comment by gcalzo** [comment]
On my MotoG5 the move internal 2 internal is still changing the timestamp... 🙁

**Comment by Ketrel** [comment]
Update just hit F-Droid this morning.
So far testing on my Oneplus 3T (only internal storage)

**Moving file from folder to folder**: Preserves Timestamp  
**Renaming file**: Changes timetamp

**Comment by gcalzo** [comment]
I have deleted my previous post because I have tried again and... **YES**, the move **internal2internal** preserves timestamp!
On my Moto G5 plus also the rename of an **internal** picture (I have used an old screenshot which are saved into the internal memory) has preserved the timestamp!

**Comment by tibbi** [comment]
Ill be working on it soon, I can make it work on sd card too.

**Comment by Ketrel** [comment]
Could you do the same renameTo for internal2internal rename operations as well?

**Comment by tibbi** [comment]
I now know how to fix everything. Copy/move/rename, Im just pretty busy now.

**Comment by tibbi** [comment]
So I somehow still managed pulling off a pretty good build 2.16.1, keeping last_modified should work in all cases. Sometimes it doesnt work to me, so some feedback would be appreciated :) The build just started rolling out, so you can either wait till you get it, or download the latest version from the [releases](https://github.com/SimpleMobileTools/Simple-Gallery/releases). Internal2Internal moving uses the proper renameTo, sd2sd still uses the old copy/delete way. Thanks

**Comment by gcalzo** [comment]
Downloaded and tested:
- move internal2internal keeps timestamps
- rename on internal keeps timestamps
- rename external sd keeps timestamps
- move sd2sd doesn't keeps timestamps... I guess because you still use copy/delete

**Comment by tibbi** [comment]
nice, so it is getting better :) I will improve it even more, thanks for the feedback.

**Comment by tibbi** [comment]
So here is a new version for testing, it should have working sd2sd too. Turns out that the SD card `renameTo` is usable only for renaming a file within the same folder, not moving it as it is at the internal `renameTo`. The proper sd card moving is available only from Android 7. Android filesystem is seriously fucked up, google really wants me to use a whole different way of copying/moving on every android version... Some people reported files being corrupt after moving from internal to internal, I couldnt reproduce it tho. Thanks for any feedback :)
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/1417375/app-release.apk.zip)

**Comment by gcalzo** [comment]
Tibbi, how can I install this zip file? It doesn't contain an APK file...

**Comment by tibbi** [comment]
Just rename the file, remove the .zip extension, then install the apk itself. I had to rename it as github doesnt allow uploading .apk files...

**Comment by gcalzo** [comment]
Uhm, are you sure to have attached the new build? On my phone I got the "do you want to upgrade the app" warning, but then the version was still **2.16.1** and nothing changed with my tests: everything work but not the move sd2sd!

**Comment by Ketrel** [comment]
If you're not rooted and using some specific tools, the upgrade would probably fail if you had the F-Droid version before due to mismatched signatures.

**Comment by tibbi** [comment]
I havent increased the app version, this is just a test build. Try uninstalling your current app first, then install the test one.

**Comment by gcalzo** [comment]
@Ketrel no, I'm not rooted and I'm not using F-Droid. I have installed it using myPhoneExplorer because it more user friendly than doing via adb... :)
@tibbi ok, I will try that!

**Comment by gcalzo** [comment]
I cannot do anything on the SD, I think because the app didn't "ask me" to authorize it to use the SD (since I have uninstalled the previous one the permission was gone).
![](https://i.imgur.com/aLz0AxM.png)

**Comment by tibbi** [comment]
find the app in Device settings and use a "Clear Data" on it, that will reset everything and reobtain the sd card path again. Sadly uninstalling an app doesnt really uninstall it, it just hides it.

**Comment by gcalzo** [comment]
Ok, that did the trick (there is always something more to learn!)
But, the move sd2sd is still updating the timestamp...

**Comment by tibbi** [comment]
okay thanks for testing. I will leave it as it is for now, it works fine to me in all cases on both Android 6 and 7 :)

**Comment by tibbi** [comment]
I will be adding a new toggle for keeping last-modified field at copy/move/rename in the next version 2.17.0, it will be enabled by default. We will see how will it go, I dont want to show an option to toggle it before every copy/move/rename.

**Comment by gcalzo** [comment]
Instead to open a new "Feature Request" I write here because it's something "related"...
Is it possibile to keep the original date/time when saving a modified file (like after a rotation?)

**Comment by tibbi** [comment]
maybe, I can take a look at it.

**Comment by tibbi** [comment]
in the next version it should be working on the internal storage, SD card fucked me up again

**Comment by gcalzo** [comment]
I got back my old Motorola Moto G2 with MarshMallow, (this one is rooted)

Tested the stock Motorola's Gallery and it works as I remembered:
- move internal2internal keeps timestamps
- move internal2sd doesn't keeps timestamps
- move sd2sd keeps timestamps
- move sd2internal doesn't keeps timestamps

Rename is not an option with this gallery app...
Now I will do te same tests using your latest app 2.18.0

**Comment by gcalzo** [comment]
Simple Gallery 2.18.0 on Motorola Moto G2 with MarshMallow

- move internal2internal keeps timestamps
- move internal2sd doesn't keeps timestamps
**- move sd2sd doesn't keeps timestamps**
- move sd2internal doesn't keeps timestamps
- rename internal2internal keeps timestamps
- rename sd2sd keeps timestamps

I will redo the tests with v2.18.0 on my MotoG5 too...

**Comment by gcalzo** [comment]
...right now v2.18.0 is still not available on Play Store for my MotoG5 so I'll wait it for the testing...

**Comment by Theobald93** [comment]
I copied pictures from folder A to folder B but the "Date Modified" changed to "now":

Open picture in folder A (Date: 06.03.2017)
Copy to... folder B
Open folder B, the picture has the right date (06.03.2017)
Open picture in folder B but no modify... the date changes instantly to NOW (05.12.2017)

All folders are on the internal storage and sorted by "Date Modified"
Setting "Keep old last-modifed value at file copy/move/rename" is activated 

Xiaomi Redmi 3
Android 7.1.2 LineageOS 14.1
SimpleGallery 2.19.0

**Comment by gcalzo** [comment]
I'm sorry @tibbi but I'm going to remove the app because even current v3.1.2 is not keeping timestamp on SD2SD move on my MotoG5...

**Comment by tibbi** [comment]
sure, if it's that important, you can remove it. 
Btw Ive replaced the renameTo with copy/delete everywhere on Android 8, theres some weird issues with files disappearing in some cases, even in other apps.

**Comment by Ketrel** [comment]
I've just updated to Android 8.1 from 7.0

Since doing so, moving/renaming is changing the timestamp again.  It was not doing so on 7.0, but is on 8.1

**Comment by Theobald93** [comment]
Move = Copy+Delete (since SimpleGallery v3.2.0 (2018-01-07)) so the timestamp changes.
https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/CHANGELOG.md

It changes on my Android 7.1.2 too when moving from internal storage to internal storage. :(

**Comment by Ketrel** [comment]
Really? That utterly blows.  That's pretty much a dealbreaker. I can't lose the sorting order every time I move an image.  If I took a picture of a pet months ago and finally move it to my 'Pets' folder for example, it should NOT be the newest image.  (For as example case)

@tibbi Is there any chance that could be undone so the timestamp does not change?

**Comment by tibbi** [comment]
fixing it is obviously on the roadmap, it just isnt that simple. Using a simple renameTo() from internal to internal caused the file to be lost to some people, which is a lot worse than shuffled files. For now I prefer safe moving.

**Comment by Ketrel** [comment]
Would it be possible for the interim to add an option (defaulting to off of course) which explains the danger, but allows the user to select to use the renameTo() method?

**Comment by tibbi** [comment]
I dont really want to add such toggles, I want to improve it the proper way.

**Comment by Ketrel** [comment]
That's fair, is there any indication of what was happening?  I'm rooted and if there's any way I can attempt to replicate the issue, I could likely grab a logcat of whatever was happening at the time.

**Comment by tibbi** [comment]
not much for you to do there, file lastModified field has been messed up since Android launched. It is something related to the system, you can read about it at https://issuetracker.google.com/issues/36930892 if you are bored. Seems like it works fine already on Google Pixel devices, it just took them 7 years to fix. Maybe in the future it will work better already.

**Comment by Ketrel** [comment]
Oh, I know that.  I meant to look at what happens to the images as far as them going missing with renameTo().

**Comment by tibbi** [comment]
well the function is misbehaving. It isnt only related to copy/move, but obviously to renaming too. If you just change one letter in a simple image file at some devices like hello.jpg to hell.jpg, it disappears. Even if it is a casual file on the internal storage. It is just one of the android mysteries. I cannot reproduce it on any of my devices or emulator, it just happens seemingly randomly to people.

**Comment by Ketrel** [comment]
I actually tested that on my Oneplus 3T.  That's exactly how I renamed it, and I couldn't reproduce it.

**Comment by tibbi** [comment]
I will try relying more on the android mediastore database containing last modified and so, working directly with the file just doesnt work. Im already fetching and updating the data there, maybe it has some glitches.

**Comment by Ketrel** [comment]
I'm not quite sure what you mean by that.  I'm probably a bit ignorant on this issue, but how would working with the android mediastore database prevent the filesystem's modification date from being affected?

**Comment by tibbi** [comment]
at sorting the items Im fetching data from the mediastore which is an internal android database with some metadata. Im not checking the Last Modified field of the file itself. That is just too unreliable and cannot be changed on SD card files.

**Comment by Ketrel** [comment]
Oh ok, that's still not the primary issue though.  It doesn't matter which method the gallery app uses to find the date for sorting.  The issue we're having is it changes the actual modification date in the filesystem.

If the the app shows an unaltered date, but it still changes on the file system, it's still something most of us cannot afford to risk happening.

Basically if the move or rename option causes the filesystem's modification date to change, then that option is destructive and not something I (and many of us) can afford to use.

As it currently stands, I have a second gallery app installed for the sole purpose of sorting files. (For the record, the app I use for this is LeafPic, which is also open source, and doesn't change the modification date on move operations).

**Comment by tibbi** [comment]
well Leafpic got abandoned even before releasing a stable app. Anyway Ill take a look at the issue someday in the future, working with files on Android is just so much harder than it looks like.

**Comment by Ketrel** [comment]
Yeah, I know. I'm saying I have keep around an app like that for the sole purpose of moving images around. I'd love to finally uninstall it, but until moving a pic doesn't change the date, I need to keep two apps.

(But since it seems to work in that app and it is open source, couldn't their method be used?)

**Comment by tibbi** [comment]
I dont want to just copy some part over, I will fix it properly someday. They might be having some issues too but since barely anyone uses that app, there arent many reports.

**Comment by Ketrel** [comment]
There's another open source app I looked at which doesn't have the timestamp issue which is more current and maybe has a better way to do it vs leafpic as a reference.

It's also on f-droid and is called Camera Roll.

Nowhere near as featured as your app, just one I tested to see if it could move images without modifying the timestamp (the method that one uses is here: https://github.com/kollerlukas/Camera-Roll-Android-App/blob/master/app/src/main/java/us/koller/cameraroll/data/fileOperations/Move.java (looks like he does a check for if you're moving to/from external vs internal and uses different methods depending))

**Comment by tibbi** [comment]
Ye, because files on the internal storage and SD card require totally different handling, but they use renameTo too. Anyway I improved the behaviour, it should work fine both on internal and SD card. A new version 3.5.3 will start rolling out tomorrow or so, please retest whenever it becomes available.

**Comment by gcalzo** [comment]
Still not working on external SD, Moto G2, Marshmallow.

**Comment by Ketrel** [comment]
3.5.3 on Oneplus 3t using LineageOS 15.1, internal storage only

- Moving files still changes the modification date  
- Refreshes  (including the automatic ones after a file copy/move) take forever.

**Comment by ramack** [comment]
The same for me. The option is checked, and I just shuffeld around 1.4k Images... A nightmare... and even worse. Simple-Gallery does not even respect the "sort by date"...

Is there any workaround to get the pictures sorted again?

**Comment by tibbi** [comment]
I dont think there is :/ File fetching has been changed so this issue might have gotten worse in some cases, Ill get to fixing it someday. It apparently never really worked properly to everyone.

**Comment by Ketrel** [comment]
Is there any possibility to add an option to use the method that some people claimed lost their files, but make it disabled by default and gives a warning to enable it?  To date, that was the only method when the date stayed correct when moving/renaming files.

**Comment by tibbi** [comment]
i dont really want to add it. Nothing improved in version 4.2.1? Sorting by Date Taken should be improved too.

**Comment by Ketrel** [comment]
That requires the pictures to have EXIF data.

I'm talking about images where  
- I've downloaded them  
- I've taken the photo and disabled EXIF data (which is every photo I've taken)
- I've been sent them as an MMS

'Date Modified' is the only viable sorting field, and if moving an image (to sort it) changes the modification date, then every image I have becomes unsortable.

**Comment by Ketrel** [comment]
And just to confirm, on 4.2.1 moving an image to another directory 100% changes the modification date.

Original File Properties: https://i.imgur.com/von0nU3.png  
After Moving To Another Folder: https://i.imgur.com/UV85shB.png

**Comment by Ketrel** [comment]
As of 4.4.4, the file modification time is still changed when moved.

Is there any way around this. Moving a file really should not cause it to be modified, it should be moved only.

**Comment by tibbi** [comment]
try selecting the image thumbnails and pressing "Fix Date Taken value"

**Comment by Ketrel** [comment]
That did not change the file modification date back to its original value. A image modified a month ago and moved to a new folder still shows that it was last modified today.

The file was modified on July 3rd.  

Afrer moving the file to a different folder, the modification date shows August 2nd.

After using 'Fix date taken value', the modification date still shows 'August 2nd'.

**Comment by tibbi** [comment]
aha right, the issue is about the date_modified, not date_taken

**Comment by Ketrel** [comment]
And specifically the filesystem modification date, not EXIF data as this applies to PNG, JPEG, and GIF as well.

**Comment by tibbi** [comment]
so I will switch back to using renameTo if moving from internal storage to internal storage in version 4.5.0. If you want to test it, let me know at hello@simplemobiletools.com so I can send you a new version there. It will affect Android 7 and 8 only.

**Comment by Ketrel** [comment]
The versions using renameTo looks like its working well. (Oneplus 3T w/ only internal storage)

**Comment by asgunassekaran** [comment]
You can use adb

 1. Enable Developer mode on mobile.
 2. Enable USG debugging on mobile.
 3. Install ADB on your laptop.
 4. Connect your mobile to your laptop using USB.
 5. Open your laptop terminal and login to your mobile using below
    commands

    adb devices
    adb shell

 6. Find the exact path where you want to put your files.
 7. Exit adb shell using the command exit.
 8. Use below command to push files to from your laptop to mobile without any metadata (created/modified time) being affected

    adb push source_path target_mobile_path

You can push folders and multiple files using the `adb push` command in one go.

You can use the same procedure and command `adb pull source_mobile_path target_laptop_path` to copy files from mobile to laptop without affecting dates.

**Comment by Ketrel** [comment]
That's not accurate.  `adb push` results in files with the current date/time as the modification time.

**Comment by asgunassekaran** [comment]
> That's not accurate. `adb push` results in files with the current date/time as the modification time.

I just tried this recently and the dates were left unaffected.

**Comment by mirh** [comment]
You are probably using superuser adb in your rom developer settings.

**Comment by asgunassekaran** [comment]
I don't know the rom developer settings. I just followed the steps I commented above. Nothing else.
